[Training]
learning_rate = 0.001
batch_size =64
nb_residual_unit = 1
consider_external_info = 1
nb_epoch = 50
finetuning_epoch=5
len_closeness = 1
len_period = 2 #unit:day
len_trend = 1 # unit:week
days_for_test=7
